### ISSUE TITLE
pipeline_server.py: TimeOut Error

### ISSUE THREAD

**Issue by JSB97** [mynlp/jigg#50]
There seems to be a bug when trying to submit long pieces of text to the pipeline_server.

To replicate the error; initiate the server as;

 submit the following text.
```
"　【ニューヨーク＝清水石珠実】「世紀の合併」と言われながら失敗した米メディア大手タイムワーナーとネット大手ＡＯＬの統合から15年。そのタイムワーナーを通信大手ＡＴ＆Ｔが買収することで、米国で業種を超えたメディア再編がまた動き出した。背景にはスマートフォン（スマホ）を通じたインターネット動画の普及がある。通信とメディア業界の境界線はこれまで以上に薄まっている。 　ネット動画を巡る異業種間合併の先駆けは2011年の米ケーブルテレビ最大手コムキャストによるＮＢＣユニバーサルの買収だ。ネット配信するコンテンツの拡充が目的で、コムキャストは今年６月にも米アニメ制作大手のドリームワークス・アニメーションを傘下に収めた。 　ＡＴ＆Ｔが狙うのもコムキャスト型のビジネスモデルで、垂直統合による複合メディア化は両社を軸に進む。 　ＡＴ＆Ｔは15年に米プロフットボールリーグ（ＮＦＬ）など人気番組の放映権を持つ衛星テレビ大手のディレクＴＶを485億ドル（約５兆円）で買収。電話契約者の頭打ちが予想される中、総売上高の３割強を占めるエンターテインメント事業の拡充を進めてきた。 　ランドール・スティーブンソン最高経営責任者（ＣＥＯ）は「世界的に優れたコンテンツを映画、テレビ、モバイル端末すべてで提供できるようになる」と買収の意義を述べた。スマホの付加価値を高め動画がもたらす広告収入も増やす考え。 　タイムワーナーも通信大手と組む事情がある。近年はネットフリックスやアマゾン・ドット・コムなど定額課金でネット動画の配信を扱うシリコンバレーの新興企業が台頭。こうした企業が独自番組の配信も始めた結果、ケーブルテレビの契約が減っている。多様化する番組配信への対応は急務だった。 　さらに20年ごろには「５Ｇ」と呼ばれる毎秒10ギガ（ギガは10億）ビットの通信速度を持つ携帯電話の無線通信規格が実用化される見込み。ネット動画配信の市場が拡大するのは確実で、買収を後押ししたとみられる。 　ただ課題もある。タイムワーナーは01年にインターネット大手ＡＯＬと経営統合したが、09年には合併を解消した。企業文化で折り合いがつかず、インターネットバブルの崩壊も影響した。異業種合併で成果をあげることは容易ではない。 　独禁当局の判断も注目だ。コンテンツがＡＴ＆Ｔに独占的に囲い込まれるのは米政府も望まない。コムキャストがＮＢＣユニバーサルを買収した際は、司法省と米連邦通信委員会の承認を得るのに１年以上かかった。米ニューヨーク・タイムズ紙はＡＴ＆Ｔが競合社向けにタイムワーナーのコンテンツ使用料をつり上げる恐れを指摘する。 　22日午前には大統領選のトランプ候補が「一握りの会社にあまりにも権力が集中している」と買収に反対する考えを表明。政治リスクもある。 　それでも米メディア企業がからむ業界再編の動きが後をたたない。 　放送業界では05年に分離したＣＢＳとバイアコムの再統合が取り沙汰される。タイムワーナーを巡っては米アップルも買収に興味を示したもよう。21世紀フォックスも数年前に買収を提案した。 　７月には米携帯首位のベライゾン・コミュニケーションズが米ヤフーの買収を決めた。傘下のネット大手ＡＯＬとの一体運営で、コンテンツ配信やデジタル広告事業の強化を目指す。 　「動画の未来はモバイル端末であり、モバイル端末の未来は動画だ」――。22日にＡＴ＆Ｔとタイムワーナーが出した記者発表文にはこんな言葉が盛り込まれた。通信とメディアの融合は今後も続きそうな気配だ。 　ＡＴ＆Ｔ　電話を発明したグラハム・ベルの電話会社を源流とする米通信大手。業界２位の米携帯業界で飽和感が強まるなか、買収を通じて「海外」「娯楽」分野を強化している。この２年間でメキシコの携帯大手２社や米衛星放送大手ディレクＴＶを買収した。競合する米携帯最大手ベライゾン・コミュニケーションズが買収で合意したヤフーのネット事業にも関心を示していた。本社はテキサス州ダラス。2015年12月通期の売上高は1468億ドル、純利益は133億ドル。 　タイムワーナー　1990年に米映画会社ワーナー・ブラザーズの親会社が出版大手タイムを買収して誕生した。「セックス・アンド・ザ・シティ」など人気ドラマの製作で定評のある有料テレビ局「ＨＢＯ」やニュース専門局「ＣＮＮ」も傘下に抱える。2001年、インターネット大手アメリカ・オンライン（ＡＯＬ）に買収されたが、相乗効果を生み出せず09年に分離。動画コンテンツ事業に特化するため14年には出版部門タイムも切り離した。15年12月通期の売上高は281億ドル、純利益は38億ドル。本社はニューヨーク市。"
```

The server returns the following error;
```
ERROR:__main__:Error: Timeout with input '"　【ニューヨーク＝清水石珠実】「世紀の合併」と言われながら失敗した米メディア大手タイムワーナーとネット大手ＡＯＬの統合から15年。そのタイムワーナーを通信大手ＡＴ＆Ｔが買収することで、米国で業種を超えたメディア再編がまた動き出した。背景にはスマートフォン（スマホ）を通じたインターネット動画の普及がある。通信とメディア業界の境界線はこれまで以上に薄まっている。 　ネット動画を巡る異業種間合併の先駆けは2011年の米ケーブルテレビ最大手コムキャストによるＮＢＣユニバーサルの買収だ。ネット配信するコンテンツの拡充が目的で、コムキャストは今年６月にも米アニメ制作大手のドリームワークス・アニメーションを傘下に収めた。 　ＡＴ＆Ｔが狙うのもコムキャスト型のビジネスモデルで、垂直統合による複合メデ?'
```
Notice that the input from the error is not the same as the input text; instead, the article seems to be truncated after ```複合メデ```, so not all data is being sent over to the server.

At first I thought it might be a mecab-problem with its buffer size (which you can change with the ```-b``` option), but this does not seem to be the case.

Looking into it a bit more - If i read the input from a  file, and break each sentence into a new line, the data is processed correctly. Is there a limit on the maximum number of characters on a line?

**Comment by kyoshinaga** [comment]
I try to reproduce that timeout error on my environment by using following steps:

1. Run pipeline server.
```bash
$ ./script/pipeline_server.py -P "-Xmx4g -cp \"jigg-0.6.1.jar:jigg-0.6.1-models.jar\" jigg.pipeline.Pipeline -annotators ssplit,mecab,jaccg"
```

2. Input your text via `client.py`. Each sentence is not broken into a new line.

```python:client.py
pipeline = PipelineClient()
f = open('./test.txt','r')
inputString = f.read()
f.close()
result = pipeline.parse(inputString)
print tostring(result, encoding='utf-8')
```

However, the timeout error does not occur when I run `client.py`. 
My current environment is below:
- Red Hat Enterprise Linux Server release 7.3 (Maipo)
- java 1.8.0_111
- python 2.7.12

Could you try the following command in the terminal? 

```bash
$java -cp "jigg-0.6.1.jar:jigg-0.6.1-models.jar" -annotators "ssplit, mecab, jaccg" -file test.txt"
```

If this command is successfully finished, you can get `test.txt.xml` in your current directory.

__test.txt.xml__:
```xml:test.txt.xml
<?xml version='1.0' encoding='UTF-8'?>
<root>
  <document id="d0">
    <sentences>
      <sentence characterOffsetEnd="64" characterOffsetBegin="0" id="s0">
        【ニューヨーク＝清水石珠実】「世紀の合併」と言われながら失敗した米メディア大手タイムワーナーとネット大手
ＡＯＬの統合から15年。
        <tokens annotators="mecab">
          <token pron="【" yomi="【" lemma="【" cForm="*" cType="*" pos3="*" pos2="*" pos1="括弧開" pos="記号" of
fsetEnd="1" offsetBegin="0" form="【" id="s0_tok0"/>
          <token pron="ニューヨーク" yomi="ニューヨーク" lemma="ニューヨーク" cForm="*" cType="*" pos3="一般" pos
2="地域" pos1="固有名詞" pos="名詞" offsetEnd="7" offsetBegin="1" form="ニューヨーク" id="s0_tok1"/>
...
```

**Comment by JSB97** [comment]
Thank you - the "-file" option helps - the output xml contains all the output of all sentences, but not the most ideal solution as I have lots of files to process.

*The problem is that pipeline-server launches Jigg in SHELL MODE.*
In shell mode there is a limit on the maximum number of characters that can be copied into the shell.

To see this, if you run;
``` $java -cp "jigg-0.6.1.jar:jigg-0.6.1-models.jar" -annotators "ssplit, mecab, jaccg" ```
and once the shell is available, try to copy a huge string (say 10x the length current string) into the shell, there will come a point where the shell cannot read any more characters/bytes. The number of characters/bytes that can be read is determined by the OS (getconf ARG_MAX)

Mac OSX (Darwin 15.2.0 Darwin Kernel Version 15.2.0: root:xnu-3248.20.55~2/RELEASE_X86_64)
java version "1.8.0_65"
Python 2.7.11

**Comment by JSB97** [comment]
Here's a bit more detail on the last comment. @tomeken-yoshinaga's is using RedHat, I am on OSX.

Size of input is governed by N_TTY_BUF_SIZE on Linux, PC_MAX_CANON and on OSX, as can be seen [here](http://pexpect.readthedocs.io/en/stable/api/pexpect.html#pexpect.spawn.send).

On Linux, the limit is 4096, on OSX its 1024. Either way there is a limit, but luckily for @tomeken-yoshinaga he can process larger articles :)

I suppose the ideal would be the ability to load files directly into the shell instead of passing the characters in the file.

**Comment by hiroshinoji** [comment]
Sorry for my too late response.

As @JSB97 suggested, the reason seems that `pexpect.spawn.send` cannot send larger size of text exceeding the maximum byte size. When I truncate the input text to the first 1022 bytes (maximum to recover all utf-8 chars) the program runs successfully.

Maybe I should implement another server in Scala, which more directly interacts with the core part of Jigg. Now CoreNLP supports CoreNLPServer, and recently this seems to become the common interface to other languages. I will investigate the same direction in the next few days.

**Comment by hiroshinoji** [comment]
I've implemented an server with Akka HTTP as well as Python interface with it.
https://github.com/mynlp/jigg/tree/develop/python

In this server, contrary to `pipeline_server.py`, users do not specify the pipeline options at starting. Rather, users call `annotate` method with properties as parameters of POST method. This is the same design as the Stanford CoreNLPServer. To avoid loading all models at different calls, the server caches the previous properties setting and do not update the pipeline if the given properties are the same as the previous ones.

**Comment by kyoshinaga** [comment]
@hiroshinoji 

I couldn't run `sbt test` on the latest `develop` branch with following error message:

```
[info] Compiling 104 Scala sources and 1 Java source to /home/kyoshinaga/work/Jigg/jigg/target/classes...
[error] /home/kyoshinaga/work/Jigg/jigg/src/main/scala/jigg/pipeline/PipelineServer.scala:197: value printHelp is not a member of jigg.pipeline.PipelineServer
[error]         server.printHelp(System.out)
[error]                ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 11 s, completed Jan 23, 2017 4:37:25 PM
```

In the `jigg.pipeli.PipelineServer`, I couldn't find the `printHelp' method.
How should I solve this error?

**Comment by hiroshinoji** [comment]
@tomeken-yoshinaga Thank you for your report. Fixed in the latest version.

**Comment by JSB97** [comment]
@hiroshinoji - thanks for the update to the server - i am having a bit of trouble initiating PipelineServer though. As described in the README;
```
$ cd jigg-0.6.2
$ java -Xmx4g -cp "*" jigg.pipeline.PipelineServer
```
Running the above returns;
```
Error: Could not find or load main class jigg.pipeline.PipelineServer
```
I have downloaded jigg-0.6.2 again, but still get the error above. Are there any steps missing in the installation perhaps?

**Comment by hiroshinoji** [comment]
@JSB97 Currently the server is only supported in the develop branch, which means manual compilation is necessary to create a jar including the server. Try the followings:

```shell
$ git clone git@github.com:mynlp/jigg.git
$ cd jigg
$ git checkout develop
$ ./bin/sbt assembly
```
Then a single jar is created in `target/jigg-assembly-0.6.2.jar`. This file should be used instead of the original `jigg-0.6.2.jar`. If you replace the original jar in the original directory with the new one (`jigg-assembly-0.6.2.jar`), the above command should work.

**Comment by JSB97** [comment]
Great - got it. Looks good so far. Server is running and got the toy example up and running.

I am using curl directly to post to the pipeline server; is there any reason why the `--data-urlencode` option does not seem to return results? (as the below code shows, there is a work around, so not a show stopper...)

As an illustrative example;
```
$ # Below returns results as expected;
curl -s --data 'あなたの名前は？' "http://localhost:8080/annotate?outputFormat=json&annotators=ssplit%2Cmecab%2Ccabocha"

$ # But the below, which should in theory be identical to the command above, complains that the annotators are not loaded 
$ curl -s --data 'あなたの名前は？' --data-urlencode "annotators=ssplit,mecab,cabocha" "http://localhost:8080/annotate?outputFormat=json"

# Server output:
[ERROR] [02/15/2017 09:01:18.725] [jigg-server-akka.actor.default-dispatcher-4] [akka://jigg-server/user/$a] Missing required option(s):
  annotators                     < str>: List of annotator names, e.g., corenlp[tokenize,ssplit],berkeleyparser (required) []
jigg.pipeline.ArgumentError: Missing required option(s):
```

**Comment by hiroshinoji** [comment]
@JSB97 The cause of this error is that the options given by `--data-urlencode` are appended to the `data` while the parameters that Jigg server detects have to be sent as in parameters of GET method.

For example, for the second input above, the server receives the data `あなたの名前は？&annotators=ssplit%2Cmecab%2Ccabocha`, and the server does not extract parameters from this input.

I don't know whether this behavior is nonstandard for POST server; for example the `post` method of python supports the `params` option, which I used in the python client implementation.

This is the same behavior as the [Stanford CoreNLP server](http://stanfordnlp.github.io/CoreNLP/corenlp-server.html#getting-started) and one way to avoid this is to use `wget` instead... Or there might be some way to send parameters separately in `curl` (?)

If this design is inconvenient to you I will examine a way to handle parameters embedded in the body.

**Comment by JSB97** [comment]
@hiroshinoji 
As soon as you use `--data` in curl, or the `data` variable in the python `requests` library, you are using the `POST` method.

Furthermore, the information attached to `--data-urlencode` in curl, and `params` in the `requests` library are variables you would want to append to the url, regardless the GET/POST method you choose.

From Jigg's design point of view, and in the context of the `python` script you have provided, combining inputs from `params` and `data` doesn't take into account how `params` and `data` variables were *intended* to be used, so arguably the current implentation is a bit of a flaw.

However - as the above examples show, manually doing the encoding so that the annotation parameters are read appropriately by Jigg isn't a lot of work; so probably not worth spending the effort on right now...

**Comment by hiroshinoji** [comment]
@JSB97 Thank you for your suggestion. It seems that the key value pairs given by `--data-urlencode` in curl are treated similarly as the key value pairs given by `data` of Python `requests` but is distinguished from `params` of `requests` in the Akka HTTP server library, on which Jigg server is based. The previous implementation could not handle key value pairs in `data` (of `requests` and hence `--data-urlencode`).

I revised the code so that the above query works correctly. This is in the latest develop branch and re-assembly is needed.

One note is that now key value pairs in `data` (in curl) are not interpreted as an text and this causes subtleties for giving input as the raw text in `data` option. Specifically if the input in `data` happens to contain `=`, the data is segmented as a key value pair and the text is not read correctly.

So now I support the new option `q`, which is recommended to use for specifying inputs. An example is:
```
$ curl -s --data 'q=あなたの名前は？' --data-urlencode "annotators=ssplit,mecab,cabocha" "http://localhost:8080/annotate?outputFormat=json"
```

The original query without `q` as above is also supported now, but only for compatibility with the previous version.

**Comment by hiroshinoji** [comment]
This also seems solved.
